name: Gradle Test
on: 
  pull_request:
  push:
    branches:
      - "main"
  
permissions:
  contents: write

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: generate-and-submit
    
    - name: Execute Gradle build
      run: ./gradlew test
